spring:
  datasource:
    url: jdbc:postgresql://postgres-notification:5432/notification_db
    username: postgres
    password: postgres
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:noreply@hrofors.ru}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

services:
  auth:
    url: http://auth-service:8081

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-must-be-at-least-32-characters-long-for-security}
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 30

logging:
  level:
    ru.itmo.notification.security: DEBUG